description: A lightweight cimg/base docker executor

parameters:
  tag:
    description: >
      A cimg/base tag

      https://hub.docker.com/r/cimg/base/tags
    type: string
    default: "current"

docker:
  - image: cimg/base:<< parameters.tag >>
    auth:
      username: $DOCKER_USERNAME
      password: $DOCKER_TOKEN
